TR_DIR ?= ../../
AMREX_HOME ?= ../../../../amrex
SUNDIALS_HOME?=/projects/co2rue/sundials

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE
USE_SUNDIALS = TRUE
USE_HYPRE=TRUE
#HYPRE_DIR=/Users/hsitaram/projects/hypre
HYPRE_DIR=/projects/co2rue/hypre

Bpack   := ./Make.package 
Blocs   := . 

include ${TR_DIR}/Make.tr
