TR_DIR ?= ../../
AMREX_HOME ?= ../../../../amrex
SUNDIALS_HOME?=/Users/hsitaram/projects/ccpc/multiscale-biomass-pyrolysis/TranspReact/sdbld

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM       = 2

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE
USE_SUNDIALS = TRUE

Bpack   := ./Make.package 
Blocs   := . 

include ${TR_DIR}/Make.tr
